from __future__ import annotations

import hashlib

SYSTEM_VERSION = "SCHOOL_L1_DB_V1"
SNAPSHOT_SOURCE = "Drive catalog / AI — Правила системы"
SNAPSHOT_DATE = "2026-08-22"

# Canonical SCHOOL_L1_DB_V1 domain rules present as ACTIVE in the Drive catalog.
# Tournament-system rules are intentionally absent. This registry is metadata only:
# it does not invent semantics for rules that the bounded evaluator has not implemented.
ACTIVE_DOMAIN_RULE_IDS = tuple(
    line.strip()
    for line in """
RULE-L1-OPEN-1H
RULE-L1-DIRECT-OVERCALL-1S
RULE-L1-COMPETITIVE-STRENGTH-PRINCIPLE
RULE-L1-CONTRACT-REQUIRED-TRICKS
RULE-L1-CONTRACT-SUCCESS
RULE-L1-OPEN-PASS-THRESHOLD
RULE-L1-MAJOR-FIT-DETECT
RULE-L1-GAME-BALANCE-25
RULE-L1-RESPONDER-STRENGTH-BANDS
RULE-L1-MAJOR-RAISE-BANDS
RULE-L1-MINOR-OPEN-CHOICE
RULE-L1-MINOR-SUPPORT-BANDS
RULE-L1-MINOR-NT-RESPONSE-BANDS
RULE-L1-SHOW-MAJOR-FIT-FIRST
RULE-L1-NEW-SUIT-MIN-LENGTH
RULE-L1-NEW-SUIT-HCP-BY-LEVEL
RULE-L1-NEW-SUIT-FORCES-OPENER
RULE-L1-OPEN-1NT
RULE-L1-1NT-NATURAL-RESPONSES
RULE-L1-1NT-STAYMAN
RULE-L1-OPEN-2C-HCP-BRANCH
RULE-L1-2C-NEGATIVE-2D
RULE-L1-WEAK2-OPEN
RULE-L1-WEAK3-OPEN
RULE-L1-WEAK4-OPEN
RULE-L1-TAKEOUT-DOUBLE
RULE-L1-TAKEOUT-DOUBLE-FORCED-RESPONSE
RULE-L1-TAKEOUT-DOUBLE-FREE-POSITION
RULE-L1-STRONG-DOUBLE-18PLUS
RULE-L1-DOUBLE-NT-RESPONSE-BANDS
RULE-L1-DOUBLE-CUEBID-GAME-FORCE
RULE-L1-NT-OVERCALL-15-17-STOPPER
RULE-L1-FALLBACK-1NT-6-10
RULE-L1-JUMP-NEW-SUIT-13PLUS-5PLUS
RULE-L1-OPEN-2NT
RULE-L1-2NT-GAME-BALANCE
RULE-L1-DISTRIBUTION-POINTS-AFTER-FIT
RULE-L1-REVALUE-AFTER-FIT
RULE-L1-SCORING-UNDOUBLED-CONTRACT
RULE-L1-SCORING-GAME-SLAM-CLASS
RULE-L1-SCORING-VUL-BONUS-UNDERTRICKS
RULE-L1-DEAL-STAGES
RULE-L1-DECLARER-ROLE
RULE-L1-AUCTION-ORDER-FINAL-CONTRACT
RULE-L1-MINOR-OPENING-PATH
RULE-L1-MINOR-RESPONSE-PRIORITY
RULE-L1-SEARCH-4CARD-MAJOR-AFTER-MINOR
RULE-L1-STRAIN-PRIORITY
RULE-L1-OPENER-SECOND-SUIT-REBID
RULE-L1-OPENER-NT-REBID
RULE-L1-2C-NEGATIVE-OPENER-REBID
RULE-L1-OVERCALL-2PLUS-LEVEL
RULE-L1-JUMP-OVERCALL-PREEMPT
RULE-L1-RESPONSE-TO-1LEVEL-OVERCALL-BANDS
RULE-L1-RESPONSE-TO-2LEVEL-OVERCALL-BANDS
RULE-L1-NT-STOPPER-REQUIRED-COMPETITION
RULE-L1-STRONG-DOUBLE-REVEAL-REBID
RULE-L1-STRONG-DOUBLE-RAISE-BANDS
RULE-L1-DOUBLE-SUIT-RESPONSE-BANDS
RULE-L1-1NT-OVERCALL-INHERITS-1NT-RESPONSES
RULE-L1-2NT-OVERCALL-RESPONSE
RULE-L1-PREEMPT-OVERCALL-RESPONSE
RULE-L1-3LEVEL-OVERCALL-RESPONSE
RULE-L1-WEAK2-RESPONSE-BANDS
RULE-L1-WEAK3-RESPONSE-BRANCHES
RULE-L1-CUEBID-AFTER-TAKEOUT-CONTINUE
RULE-L1-STRONG-DOUBLE-OWN-SUIT-REBID
RULE-L1-STRONG-DOUBLE-NT-REBID
RULE-L1-SHAPE-CLASSIFICATION
RULE-L1-HCP-CONTRACT-LEVEL-GUIDE
RULE-L1-TABLE-CARD-ORIENTATION
RULE-L1-OPEN-1S
RULE-L1-DIRECT-OVERCALL-1SUIT
RULE-L1-1NT-TRANSFER-ENTRY-GENERIC
RULE-L1-1NT-TRANSFER-SECOND-BID
RULE-L1-1NT-STAYMAN-OPENER-RESPONSE
RULE-L1-1NT-STAYMAN-RESPONDER-CONTINUE
RULE-L1-2NT-TRANSFER-STAYMAN-SHIFT
RULE-L1-PLAY-NT-COUNT-TOP-TRICKS
RULE-L1-PLAY-NT-FIND-EXTRA-TRICKS
RULE-L1-PLAY-PRESERVE-ENTRIES
RULE-L1-PLAY-AVOID-BLOCKING
RULE-L1-PLAY-FINESSE-PLAN
RULE-L1-PLAY-EXPASS-PLAN
RULE-L1-PLAY-ESTABLISH-LONG-SUIT
RULE-L1-PLAY-TRUMP-COUNT-LOSERS
RULE-L1-PLAY-DISCARD-LOSER-ON-WINNER
RULE-L1-PLAY-RUFF-LOSER-SHORT-TRUMP
RULE-L1-PLAY-DRAW-TRUMPS-TIMING
RULE-L1-PLAY-NT-PRESERVE-STOPPERS
RULE-L1-LESSON2-RESPONDER-AFTER-1M
RULE-L1-1M-NT-RESPONSE-BANDS-CONTEXT
RULE-L1-OPENER-BALANCE-AFTER-RESPONSE
RULE-L1-PREFER-3NT-OVER-5MINOR-BASIC
RULE-L1-OPENER-REBID-PURPOSE
RULE-L1-OPENER-SUPPORT-RESPONDER-NEW-SUIT
RULE-L1-OPENER-REPEAT-OWN-SUIT-6PLUS
RULE-L1-OPENER-PASS-AFTER-RESPONSE-FORCING-CHECK
RULE-L1-NATURAL-VS-ARTIFICIAL-ALERT
RULE-L1-PREEMPT-PURPOSE
RULE-L1-STRONG2C-SUIT-REBID-CONTINUE
RULE-L1-DOUBLE-MEANING-BY-CONTEXT
RULE-L1-DOUBLE-INITIAL-AMBIGUITY
RULE-L1-WEAK2-OPENER-ACCEPT-INVITE
RULE-L1-TAKEOUT-DOUBLE-REBID-BALANCE
RULE-L1-PENALTY-PASS-ON-DOUBLE-CONTEXT
RULE-L1-RESPONDER-REEVALUATE-AFTER-OPENER-REBID
RULE-L1-DECK-RANK-SUIT-HIERARCHY
RULE-L1-HCP-COUNT
RULE-L1-TRICK-WINNER
RULE-L1-TAKEOUT-DOUBLE-NT-OVER-MINOR
""".splitlines()
    if line.strip()
)

GOVERNANCE_RULE_IDS = (
    "RULE-L1-MACHINE-COMPILER-GATE",
    "RULE-L1-RUNTIME-CONFLICT-GATE",
)

# These statuses are copied from the current 121-Skill L1 graph. They are gates,
# not executable promotions.
PARTIAL_SKILL_IDS = frozenset(
    {
        "SKILL-0012",
        "SKILL-0013",
        "SKILL-0076",
        "SKILL-0077",
        "SKILL-0078",
        "SKILL-0079",
        "SKILL-0080",
        "SKILL-0082",
        "SKILL-0083",
        "SKILL-0084",
        "SKILL-0085",
        "SKILL-0086",
        "SKILL-0087",
        "SKILL-0088",
        "SKILL-0119",
        "SKILL-0120",
        "SKILL-0121",
    }
)
BLOCKED_SKILL_IDS = frozenset({"SKILL-0081"})
ALL_SKILL_IDS = tuple(f"SKILL-{number:04d}" for number in range(1, 122))
APPROVED_SKILL_IDS = tuple(
    skill_id
    for skill_id in ALL_SKILL_IDS
    if skill_id not in PARTIAL_SKILL_IDS and skill_id not in BLOCKED_SKILL_IDS
)

KNOWN_RULE_IDS = frozenset(ACTIVE_DOMAIN_RULE_IDS) | frozenset(GOVERNANCE_RULE_IDS)
RULE_ID_FINGERPRINT = hashlib.sha256(
    "\n".join(sorted(ACTIVE_DOMAIN_RULE_IDS)).encode("utf-8")
).hexdigest()
EXPECTED_RULE_ID_FINGERPRINT = "143d7387734a721ebedd6cab78af21278f7b250d963ee2c82562e50dc3bbfd33"


def classify_rule(rule_id: str) -> str:
    if rule_id in ACTIVE_DOMAIN_RULE_IDS:
        return "DOMAIN"
    if rule_id in GOVERNANCE_RULE_IDS:
        return "GOVERNANCE"
    return "UNKNOWN"


def validate_registry() -> None:
    checks = {
        "domain_rule_count": (len(ACTIVE_DOMAIN_RULE_IDS), 111),
        "domain_rule_unique": (len(set(ACTIVE_DOMAIN_RULE_IDS)), 111),
        "governance_rule_count": (len(GOVERNANCE_RULE_IDS), 2),
        "skill_count": (len(ALL_SKILL_IDS), 121),
        "approved_skill_count": (len(APPROVED_SKILL_IDS), 103),
        "partial_skill_count": (len(PARTIAL_SKILL_IDS), 17),
        "blocked_skill_count": (len(BLOCKED_SKILL_IDS), 1),
    }
    failures = [
        f"{name}={actual}, expected={expected}"
        for name, (actual, expected) in checks.items()
        if actual != expected
    ]
    if RULE_ID_FINGERPRINT != EXPECTED_RULE_ID_FINGERPRINT:
        failures.append(
            "rule_id_fingerprint="
            f"{RULE_ID_FINGERPRINT}, expected={EXPECTED_RULE_ID_FINGERPRINT}"
        )
    if frozenset(PARTIAL_SKILL_IDS) & frozenset(BLOCKED_SKILL_IDS):
        failures.append("partial and blocked Skill sets overlap")
    if failures:
        raise RuntimeError("L1 canonical registry integrity failure: " + "; ".join(failures))


validate_registry()
