-- Synthetic protocol model only. NOT a reconstructed production schema.
CREATE SCHEMA sim AUTHORIZATION rep_owner;
SET ROLE rep_owner;
CREATE TABLE sim.task(id bigint PRIMARY KEY, task_key text UNIQUE NOT NULL, status text NOT NULL);
CREATE TABLE sim.outbox(id bigint PRIMARY KEY, task_id bigint REFERENCES sim.task(id),
  idem text UNIQUE NOT NULL, payload_hash text NOT NULL, outcome text NOT NULL CHECK(outcome IN ('PENDING','UNKNOWN','DONE')));
CREATE TABLE sim.receipt(idem text PRIMARY KEY REFERENCES sim.outbox(idem), payload_hash text NOT NULL, result text NOT NULL);
CREATE TABLE sim.event(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint REFERENCES sim.task(id), payload jsonb NOT NULL);
CREATE SEQUENCE sim.unused_seq START 50;
CREATE FUNCTION sim.accept_receipt(k text,h text,r text) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,sim AS $$
DECLARE oldhash text; oldresult text;
BEGIN
  IF k IS NULL OR h IS NULL OR r IS NULL THEN RAISE EXCEPTION 'RECEIPT_NULL'; END IF;
  PERFORM 1 FROM sim.outbox WHERE idem=k AND payload_hash=h FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'RECEIPT_IDENTITY'; END IF;
  SELECT payload_hash,result INTO oldhash,oldresult FROM sim.receipt WHERE idem=k;
  IF FOUND THEN
    IF oldhash IS DISTINCT FROM h OR oldresult IS DISTINCT FROM r THEN RAISE EXCEPTION 'RECEIPT_CONFLICT'; END IF;
    RETURN oldresult;
  END IF;
  INSERT INTO sim.receipt VALUES(k,h,r);
  UPDATE sim.outbox SET outcome='DONE' WHERE idem=k;
  RETURN r;
END $$;
CREATE FUNCTION sim.claim(k text) RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,sim AS $$
DECLARE result text;
BEGIN
  SELECT outcome INTO result FROM sim.outbox WHERE idem=k FOR UPDATE;
  IF result IS DISTINCT FROM 'PENDING' THEN RETURN 'HOLD'; END IF;
  UPDATE sim.outbox SET outcome='UNKNOWN' WHERE idem=k;
  RETURN 'SEND_ONCE';
END $$;
CREATE FUNCTION sim.immutable_receipt() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $$
BEGIN RAISE EXCEPTION 'IMMUTABLE_RECEIPT'; END $$;
CREATE TRIGGER receipt_immutable BEFORE UPDATE OR DELETE ON sim.receipt FOR EACH ROW EXECUTE FUNCTION sim.immutable_receipt();
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA sim FROM PUBLIC;
GRANT USAGE ON SCHEMA sim TO rep_worker,rep_callback,rep_health;
GRANT EXECUTE ON FUNCTION sim.claim(text) TO rep_worker;
GRANT EXECUTE ON FUNCTION sim.accept_receipt(text,text,text) TO rep_callback;
GRANT SELECT ON ALL TABLES IN SCHEMA sim TO rep_health;
ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
INSERT INTO sim.task VALUES(1,'fixture-1','READY');
INSERT INTO sim.outbox VALUES(1,1,'fixture-dispatch-1','synthetic-hash','UNKNOWN');
INSERT INTO sim.outbox VALUES(2,1,'fixture-dispatch-2','synthetic-hash-2','PENDING');
INSERT INTO sim.event(task_id,payload) VALUES(1,'{"text":"synthetic","optional":null}'),(1,'{"text":"синтетика","n":2}');
SELECT setval('sim.event_id_seq',100,true);
RESET ROLE;
